<a href="https://colab.research.google.com/github/Tamondong-Ivan-Rex-B/CPE-031-Visualization-and-Data-Analysis/blob/ALL-DEMOS-CPE-031_TAMONDONG/DEMO_2_Data_Analysis_September_11%2C_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introducing Data Analysis

Data analysis is a process of inspecting, cleansing, transformation, and modeling data with the goal of discovering useful information, informing conclusions, and supporting decision-making.


Data analysis - It is a detailed examination of the elements of structure of something

Data analytics - It is a systematic computational analysis of something


Types of Data Analysis

Descriptive Analysis - is the most common and primary forms of data analysis. It is used to find the "what is/has happening/happened?" in business. usually, we take to help of descriptive data analysis to track the Key Performance Indicator (KPIs), sales profit/loss, and so on. Example - Publishing weekly sales report

Diagnostic data analysis helps to find out the "why did something happen?" Once we get the report of what happened from descriptive analysis, diagnostic data analysis helps us understand which factors caused something to happen. Example - analyzing the reasons/factors for fewer sales in the previous year

Prescriptive analysis uses the ourcomes of all the data analysis. It will help find the "what action should be taken?". So, it prescribes the action/s as a solution to counter the specific situation. It needs advance machine learning and real-time AI. Example - Dynamic pricing of taxi fares depends on demand, weather, and social conditions.

Data Analysis Process Flow
Requirements, Gathering and Planning > di ko mabasa yung dilaw > Data Cleansing > Data Preparation > Data Analysis > Data Interpretation and Result Summarization > Data Visualization

Pandas
- Pandas is a trendy data analysis and data exploration library that provides a astructured representation of data. It helps to do data manipulation, cleansing, aggregation, merging and effortlessly. (conda install pandas, pip install pandas, !pip install pandas)

Series - Pandas series is one-dimensional array with index labels, more in technical term these ...

Series - is essentially column

DataFrame - multi-dimensional table made up of collection of series

In [2]:
#Example 1

import pandas as pd
data = {
    'apples':[3, 2, 0, 1],
    'oranges':[0, 3, 7, 2]
}
purchases = pd.DataFrame(data)
print(purchases)

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [3]:
#Example 2 DataFrame Index
import pandas as pd
data = {
    'apples':[3, 2, 0, 1],
    'oranges':[0, 3, 7, 2]
}
purchases = pd.DataFrame(data, index=['June', 'Robert', 'Lily', 'David'])
print(purchases)

        apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [4]:
#Example 3 Locate - locate specific record

print(purchases.loc['June'])

apples     3
oranges    0
Name: June, dtype: int64

In [5]:
#Example 4 Importing DataFrame to csv or excel file

purchases.to_csv('purchases.csv') # or purchases.to_excel('purchases.xlsx')

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [8]:
df  = pd.read_excel('/content/drive/Othercomputers/My Laptop/TIP QC/TIP/Computer Engineering/2ND YEAR/1ST SEMESTER/CPE 031 Visualizations and Data Analysis/Midterms/Untitled folder/ComputerData.xlsx')

In [9]:
print(df)

   Computer ID   Brand        Model    Processor  RAM (GB)  Storage (GB)  \
0            1    Dell       XPS 13     Intel i7        16           512
1            2      HP  Pavilion 15  AMD Ryzen 5         8           256
2            3   Apple  MacBook Pro     Apple M1        16          1024
3            4  Lenovo  ThinkPad X1     Intel i9        32           512
4            5    Asus   ZenBook 14     Intel i5        16           512

      Graphics Card  Price ($)
0     Intel Iris Xe       1200
1        AMD Radeon        800
2  Apple Integrated       2400
3   NVIDIA GTX 1650       1800
4      NVIDIA MX250       1000

In [10]:
df

,Computer ID,Brand,Model,Processor,RAM (GB),Storage (GB),Graphics Card,Price ($)
0,1,Dell,XPS 13,Intel i7,16,512,Intel Iris Xe,1200
1,2,HP,Pavilion 15,AMD Ryzen 5,8,256,AMD Radeon,800
2,3,Apple,MacBook Pro,Apple M1,16,1024,Apple Integrated,2400
3,4,Lenovo,ThinkPad X1,Intel i9,32,512,NVIDIA GTX 1650,1800
4,5,Asus,ZenBook 14,Intel i5,16,512,NVIDIA MX250,1000

In [11]:
# Display data that has 512gb

df.loc[df['Storage (GB)'] == 512]

,Computer ID,Brand,Model,Processor,RAM (GB),Storage (GB),Graphics Card,Price ($)
0,1,Dell,XPS 13,Intel i7,16,512,Intel Iris Xe,1200
3,4,Lenovo,ThinkPad X1,Intel i9,32,512,NVIDIA GTX 1650,1800
4,5,Asus,ZenBook 14,Intel i5,16,512,NVIDIA MX250,1000